<a href="https://colab.research.google.com/github/mikysetiawan/MachineLearningExpert/blob/master/Learning_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import time

In [2]:
@tf.function
def my_function(x):
    print("Inside function:", x)
    return x

print(my_function(tf.constant(5)))
print(my_function(tf.constant(10)))

Inside function: Tensor("x:0", shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


Kenapa hasilnya di print hanya 1x? inilah perbedaan fungsi tensorflow dengan python biasa

Lalu kita coba latihan membuat variable tensorflow seperti dibawah, ada variable biasa ada konstanta

In [4]:
import tensorflow as tf

a = tf.Variable(3)
b = tf.constant(3)

a.assign(5)
# b.assign(5)

print("Nilai a:", a)
print("Nilai b:", b)

Nilai a: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
Nilai b: tf.Tensor(3, shape=(), dtype=int32)


INDEXING & SLICING

In [4]:
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])

elemen_pertama = tensor1[0,0]
baris_pertama = tensor1[0]
kolom_pertama = tensor1[:,0]

print(elemen_pertama)
print(baris_pertama)
print(kolom_pertama)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)


In [5]:
tensor2 = tf.constant([9, 4, 2, 3, 7, 5, 6])

slicing = tf.slice(tensor2, begin=[1], size=[3])

print(slicing)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


RESHAPING

In [7]:
tensor3 = tf.constant([1, 2, 3, 4])

reshaped_41 = tf.reshape(tensor3, (4, 1))
reshaped_22 = tf.reshape(tensor3, (2, 2))

print(tensor3)
print(reshaped_41)
print(reshaped_22)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


REDUCING

* without axis = sum all
* axis 0 = sum column
* axis 1 = sum row

In [9]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

sum_all = tf.reduce_sum(tensor)
sum_axis0 = tf.reduce_sum(tensor, axis=0)
sum_axis1 = tf.reduce_sum(tensor, axis=1)

print(tensor)
print(sum_all)
print(sum_axis0)
print(sum_axis1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 6 15], shape=(2,), dtype=int32)


In [10]:
tensor1 = tf.constant([5, 6, 7])
tensor2 = tf.constant([3, 2, 1])

added = tf.add(tensor1, tensor2)
print(added)

tf.Tensor([8 8 8], shape=(3,), dtype=int32)


EAGER MODE VS GRAPH MODE

In [13]:
def kalkulasi_rumit_eager(x):
  total = tf.constant(0.0)
  for i in tf.range(100000):
    total += tf.cast(i, dtype=tf.float32) * x
  return total


start_time = time.time()
hasil = kalkulasi_rumit_eager(tf.constant(2.0))
end_time = time.time()


print(f"Hasil Eager Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Eager Mode: {end_time - start_time:.4f} detik")

Hasil Eager Mode: 9999780864.0
Waktu Eksekusi Eager Mode: 37.7612 detik


In [14]:
@tf.function
def kalkulasi_rumit_graph(x):
  total = tf.constant(0.0)
  for i in tf.range(100000):
    total += tf.cast(i, dtype=tf.float32) * x
  return total

# Mengukur waktu eksekusi pertama kali
print("Eksekusi Pertama Graph (Kompilasi)")
start_time = time.time()
hasil = kalkulasi_rumit_graph(tf.constant(2.0))
end_time = time.time()

print(f"Hasil Graph Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Pertama Graph: {end_time - start_time:.4f} detik")

# Mengukur waktu eksekusi kedua
print("Eksekusi Kedua Graph")
start_time = time.time()
hasil = kalkulasi_rumit_graph(tf.constant(2.0))
end_time = time.time()

print(f"Hasil Graph Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Kedua Graph: {end_time - start_time:.4f} detik")

Eksekusi Pertama Graph (Kompilasi)
Hasil Graph Mode: 9999780864.0
Waktu Eksekusi Pertama Graph: 0.7286 detik
Eksekusi Kedua Graph
Hasil Graph Mode: 9999780864.0
Waktu Eksekusi Kedua Graph: 0.6323 detik
