<a href="https://colab.research.google.com/github/mikysetiawan/MachineLearningExpert/blob/master/Learning_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import time

In [ ]:
@tf.function
def my_function(x):
    print("Inside function:", x)
    return x

print(my_function(tf.constant(5)))
print(my_function(tf.constant(10)))

Inside function: Tensor("x:0", shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


Kenapa hasilnya di print hanya 1x? inilah perbedaan fungsi tensorflow dengan python biasa

Lalu kita coba latihan membuat variable tensorflow seperti dibawah, ada variable biasa ada konstanta

In [ ]:
import tensorflow as tf

a = tf.Variable(3)
b = tf.constant(3)

a.assign(5)
# b.assign(5)

print("Nilai a:", a)
print("Nilai b:", b)

Nilai a: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
Nilai b: tf.Tensor(3, shape=(), dtype=int32)


INDEXING & SLICING

In [ ]:
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])

elemen_pertama = tensor1[0,0]
baris_pertama = tensor1[0]
kolom_pertama = tensor1[:,0]

print(elemen_pertama)
print(baris_pertama)
print(kolom_pertama)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)


In [ ]:
tensor2 = tf.constant([9, 4, 2, 3, 7, 5, 6])

slicing = tf.slice(tensor2, begin=[1], size=[3])

print(slicing)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


RESHAPING

In [ ]:
tensor3 = tf.constant([1, 2, 3, 4])

reshaped_41 = tf.reshape(tensor3, (4, 1))
reshaped_22 = tf.reshape(tensor3, (2, 2))

print(tensor3)
print(reshaped_41)
print(reshaped_22)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


REDUCING

* without axis = sum all
* axis 0 = sum column
* axis 1 = sum row

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

sum_all = tf.reduce_sum(tensor)
sum_axis0 = tf.reduce_sum(tensor, axis=0)
sum_axis1 = tf.reduce_sum(tensor, axis=1)

print(tensor)
print(sum_all)
print(sum_axis0)
print(sum_axis1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 6 15], shape=(2,), dtype=int32)


In [ ]:
tensor1 = tf.constant([5, 6, 7])
tensor2 = tf.constant([3, 2, 1])

added = tf.add(tensor1, tensor2)
print(added)

tf.Tensor([8 8 8], shape=(3,), dtype=int32)


EAGER MODE VS GRAPH MODE

In [ ]:
def kalkulasi_rumit_eager(x):
  total = tf.constant(0.0)
  for i in tf.range(100000):
    total += tf.cast(i, dtype=tf.float32) * x
  return total


start_time = time.time()
hasil = kalkulasi_rumit_eager(tf.constant(2.0))
end_time = time.time()


print(f"Hasil Eager Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Eager Mode: {end_time - start_time:.4f} detik")

Hasil Eager Mode: 9999780864.0
Waktu Eksekusi Eager Mode: 37.7612 detik


In [ ]:
@tf.function
def kalkulasi_rumit_graph(x):
  total = tf.constant(0.0)
  for i in tf.range(100000):
    total += tf.cast(i, dtype=tf.float32) * x
  return total

# Mengukur waktu eksekusi pertama kali
print("Eksekusi Pertama Graph (Kompilasi)")
start_time = time.time()
hasil = kalkulasi_rumit_graph(tf.constant(2.0))
end_time = time.time()

print(f"Hasil Graph Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Pertama Graph: {end_time - start_time:.4f} detik")

# Mengukur waktu eksekusi kedua
print("Eksekusi Kedua Graph")
start_time = time.time()
hasil = kalkulasi_rumit_graph(tf.constant(2.0))
end_time = time.time()

print(f"Hasil Graph Mode: {hasil.numpy()}")
print(f"Waktu Eksekusi Kedua Graph: {end_time - start_time:.4f} detik")

Eksekusi Pertama Graph (Kompilasi)
Hasil Graph Mode: 9999780864.0
Waktu Eksekusi Pertama Graph: 0.7286 detik
Eksekusi Kedua Graph
Hasil Graph Mode: 9999780864.0
Waktu Eksekusi Kedua Graph: 0.6323 detik


# Custom Model

In [4]:
# SEQUENTAL API

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

seq_model = Sequential([
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
    ])

print(seq_model)

<Sequential name=sequential_2, built=False>


In [12]:
# FUNCTIONAL API

from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Input

#Inisiasi input layer
input_layer = Input(shape=(4,))

#Susun layer yang terhubung hingga ke output layer (saling terhubung / sequental)
dense_1 = Dense(128, activation='relu')(input_layer)
dense_2 = Dense(64, activation='relu')(dense_1)
dense_3 = Dense(32, activation='relu')(dense_2)
dense_4 = Dense(16, activation='tanh')(dense_3)
output_layer = Dense(1, activation='sigmoid')(dense_4)

#Deklarasikan model dengan input dan output
model = Model(inputs=input_layer, outputs=output_layer)

print(model)

# ATAU dibuat paralel 1 to many
layer_1 = Dense(128, activation='relu')(input_layer)
layer_2 = Dense(32, activation="relu")(layer_1)
layer_3 = Dense(64, activation="relu")(layer_1)
layer_4 = Dense(16, activation="tanh")(layer_1)

print(layer_4)

# Bisa digabung lagi
from tensorflow.keras.layers import Concatenate
merge = Concatenate([layer_2, layer_3, layer_4])

print(merge)

# mutliple output
output_2 = Dense(1)(layer_2)
output_3 = Dense(1)(layer_3)
output_4 = Dense(1)(layer_4)

<Functional name=functional_5, built=True>
<KerasTensor shape=(None, 16), dtype=float32, sparse=False, ragged=False, name=keras_tensor_61>
<Concatenate name=concatenate_3, built=False>


In [20]:
# SIAMESE NETWORK, Multiple input

from tensorflow import keras
from tensorflow.keras.layers import Flatten, Dropout

def build_base_network(input_shape):
    input_layer = Input(shape=input_shape)
    x = Flatten()(input_layer)
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.2)(x)
    x = Dense(128, activation='relu')(x)
    return Model(inputs=input_layer, outputs=x)

input_a = Input(shape=(28, 28,))
input_b = Input(shape=(28, 28,))


vec_a = build_base_network(input_a.shape[1:])
vec_b = build_base_network(input_b.shape[1:])

output = keras.ops.sqrt(keras.ops.sum(keras.ops.square(vec_a(input_a) - vec_b(input_b)), axis=1, keepdims=True))
siamese_net = Model(inputs=[input_a, input_b], outputs=output)

print(siamese_net)

<Functional name=functional_17, built=True>


In [ ]:
# Customize Loss function

def mean_squared_error(y_true, y_pred):
    loss = tf.reduce_mean(tf.square(y_true - y_pred))
    return loss

def huber_loss(y_true, y_pred):
  threshold = 1
  error = y_true - y_pred
  is_small_error = tf.abs(error) <= threshold
  squared_loss = 0.5 * tf.square(error)
  linear_loss = threshold * (tf.abs(error) - 0.5 * threshold)
  # where is_small_error ? squared_loss : linear_loss
  loss = tf.where(is_small_error, squared_loss, linear_loss)

  return tf.reduce_mean(loss)


def huber_loss_with_treshold(threshold):
  def huber_loss(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) <= threshold
    squared_loss = 0.5 * tf.square(error)
    linear_loss = threshold * (tf.abs(error) - 0.5 * threshold)
    loss = tf.where(is_small_error, squared_loss, linear_loss)

    return tf.reduce_mean(loss)
  return huber_loss


model.compile(loss = huber_loss_with_threshold(threshold=1), optimizer='adam')


from tensorflow.keras.losses import Loss

class HuberLoss(Loss):
    def __init__(self, threshold=1.0):
      super().__init__()
      self.threshold = threshold

    def call(self, y_true, y_pred):
      error = y_true - y_pred
      is_small_error = tf.abs(error) <= self.threshold
      squared_loss = 0.5 * tf.square(error)
      linear_loss = self.threshold * (tf.abs(error) - 0.5 * self.threshold)
      loss = tf.where(is_small_error, squared_loss, linear_loss)

      return tf.reduce_mean(loss)